# Render deployment configuration for July24Academy

services:
  # Web service
  - type: web
    name: july24academy
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: /var/data/july24academy.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1

  # Database service (SQLite)
  # Since SQLite is a file-based database, we don't need a separate service
  # We're using a persistent disk mounted to the web service instead

# Environment variables
envVarGroups:
  - name: july24academy-env
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
